image: node:9.4.0

stages:
    - test
    - codepush

test:
    stage: test
    before_script:
        - npm install
    script:
        - npm test
    cache:
        paths:
            - node_modules/

codepush:
    stage: codepush
    before_script:
        - npm install
        - npm install -g appcenter-cli
    script:
        - appcenter codepush release-react -a dryvo/dryvo -d Production --token $APPCENTER_TOKEN
    when: on_success
    only:
        - production
    cache:
        paths:
            - node_modules/
